package com.apijccp.dao;

public class RolUsu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rol_usu.ID_USUARIO
	 * @mbg.generated  Sat May 16 21:56:03 CEST 2020
	 */
	private Integer idUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rol_usu.COD_ROL
	 * @mbg.generated  Sat May 16 21:56:03 CEST 2020
	 */
	private String codRol;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rol_usu.ID_USUARIO
	 * @return  the value of rol_usu.ID_USUARIO
	 * @mbg.generated  Sat May 16 21:56:03 CEST 2020
	 */
	public Integer getIdUsuario() {
		return idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rol_usu.ID_USUARIO
	 * @param idUsuario  the value for rol_usu.ID_USUARIO
	 * @mbg.generated  Sat May 16 21:56:03 CEST 2020
	 */
	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rol_usu.COD_ROL
	 * @return  the value of rol_usu.COD_ROL
	 * @mbg.generated  Sat May 16 21:56:03 CEST 2020
	 */
	public String getCodRol() {
		return codRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rol_usu.COD_ROL
	 * @param codRol  the value for rol_usu.COD_ROL
	 * @mbg.generated  Sat May 16 21:56:03 CEST 2020
	 */
	public void setCodRol(String codRol) {
		this.codRol = codRol == null ? null : codRol.trim();
	}
}