package com.apijccp.dao;

import java.util.ArrayList;
import java.util.List;

public class RolUsuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    public RolUsuExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdUsuarioIsNull() {
            addCriterion("ID_USUARIO is null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIsNotNull() {
            addCriterion("ID_USUARIO is not null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioEqualTo(Integer value) {
            addCriterion("ID_USUARIO =", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotEqualTo(Integer value) {
            addCriterion("ID_USUARIO <>", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGreaterThan(Integer value) {
            addCriterion("ID_USUARIO >", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_USUARIO >=", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLessThan(Integer value) {
            addCriterion("ID_USUARIO <", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioLessThanOrEqualTo(Integer value) {
            addCriterion("ID_USUARIO <=", value, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIn(List<Integer> values) {
            addCriterion("ID_USUARIO in", values, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotIn(List<Integer> values) {
            addCriterion("ID_USUARIO not in", values, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioBetween(Integer value1, Integer value2) {
            addCriterion("ID_USUARIO between", value1, value2, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_USUARIO not between", value1, value2, "idUsuario");
            return (Criteria) this;
        }

        public Criteria andCodRolIsNull() {
            addCriterion("COD_ROL is null");
            return (Criteria) this;
        }

        public Criteria andCodRolIsNotNull() {
            addCriterion("COD_ROL is not null");
            return (Criteria) this;
        }

        public Criteria andCodRolEqualTo(String value) {
            addCriterion("COD_ROL =", value, "codRol");
            return (Criteria) this;
        }

        public Criteria andCodRolNotEqualTo(String value) {
            addCriterion("COD_ROL <>", value, "codRol");
            return (Criteria) this;
        }

        public Criteria andCodRolGreaterThan(String value) {
            addCriterion("COD_ROL >", value, "codRol");
            return (Criteria) this;
        }

        public Criteria andCodRolGreaterThanOrEqualTo(String value) {
            addCriterion("COD_ROL >=", value, "codRol");
            return (Criteria) this;
        }

        public Criteria andCodRolLessThan(String value) {
            addCriterion("COD_ROL <", value, "codRol");
            return (Criteria) this;
        }

        public Criteria andCodRolLessThanOrEqualTo(String value) {
            addCriterion("COD_ROL <=", value, "codRol");
            return (Criteria) this;
        }

        public Criteria andCodRolLike(String value) {
            addCriterion("COD_ROL like", value, "codRol");
            return (Criteria) this;
        }

        public Criteria andCodRolNotLike(String value) {
            addCriterion("COD_ROL not like", value, "codRol");
            return (Criteria) this;
        }

        public Criteria andCodRolIn(List<String> values) {
            addCriterion("COD_ROL in", values, "codRol");
            return (Criteria) this;
        }

        public Criteria andCodRolNotIn(List<String> values) {
            addCriterion("COD_ROL not in", values, "codRol");
            return (Criteria) this;
        }

        public Criteria andCodRolBetween(String value1, String value2) {
            addCriterion("COD_ROL between", value1, value2, "codRol");
            return (Criteria) this;
        }

        public Criteria andCodRolNotBetween(String value1, String value2) {
            addCriterion("COD_ROL not between", value1, value2, "codRol");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rol_usu
     *
     * @mbg.generated do_not_delete_during_merge Sat May 16 23:02:23 CEST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rol_usu
     *
     * @mbg.generated Sat May 16 23:02:23 CEST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}