package com.apijccp.dao;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import java.util.Date;

public class UsuarioWeb {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario_web.ID_USUARIO
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	private Integer idUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario_web.COD_USUARIO
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	private String codUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario_web.PASSWORD
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario_web.TIP_ESTADO
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	private TipEstado tipEstado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario_web.FEC_CADUCIDAD_PASS
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	private Date fecCaducidadPass;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario_web.ID_USUARIO
	 * @return  the value of usuario_web.ID_USUARIO
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	public Integer getIdUsuario() {
		return idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario_web.ID_USUARIO
	 * @param idUsuario  the value for usuario_web.ID_USUARIO
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario_web.COD_USUARIO
	 * @return  the value of usuario_web.COD_USUARIO
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	public String getCodUsuario() {
		return codUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario_web.COD_USUARIO
	 * @param codUsuario  the value for usuario_web.COD_USUARIO
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	public void setCodUsuario(String codUsuario) {
		this.codUsuario = codUsuario == null ? null : codUsuario.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario_web.PASSWORD
	 * @return  the value of usuario_web.PASSWORD
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario_web.PASSWORD
	 * @param password  the value for usuario_web.PASSWORD
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario_web.TIP_ESTADO
	 * @return  the value of usuario_web.TIP_ESTADO
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	public TipEstado getTipEstado() {
		return tipEstado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario_web.TIP_ESTADO
	 * @param tipEstado  the value for usuario_web.TIP_ESTADO
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	public void setTipEstado(TipEstado tipEstado) {
		this.tipEstado = tipEstado == null ? null : tipEstado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario_web.FEC_CADUCIDAD_PASS
	 * @return  the value of usuario_web.FEC_CADUCIDAD_PASS
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	public Date getFecCaducidadPass() {
		return fecCaducidadPass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario_web.FEC_CADUCIDAD_PASS
	 * @param fecCaducidadPass  the value for usuario_web.FEC_CADUCIDAD_PASS
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	public void setFecCaducidadPass(Date fecCaducidadPass) {
		this.fecCaducidadPass = fecCaducidadPass;
	}

	private static final Logger logger = LogManager.getLogger(UsuarioWeb.class);

	public enum TipEstado {
		BAJA("BA"),
		TRAMITACION_BAJA ("TB"),
		TRAMITACION_ALTA ("TA"),
		ALTA("AL");

		private String estado;
		
		TipEstado(String estado) {
			this.estado = estado;
		}
		public String getEstado() {
			return estado;
		}
		
		public static TipEstado getTipEstado(String estado) {
			TipEstado salida = null;
			for (TipEstado tipEstado :TipEstado.values()) {
				if (tipEstado.getEstado().equalsIgnoreCase(estado)) {
					salida = tipEstado;
				}
			}
			
			if (salida == null) {
				System.out.println("PONER MENSAJE ERROR!! IMPLEMENTAR LOGGER "+estado);
			}
			logger.error("ESTO ES UN MENSAJE DE PRUEBA! "+salida);
			return salida;
		}
		
	}
}