package com.apijccp.dao.mysql.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.apijccp.dao.RolUsuExample;
import com.apijccp.dao.RolUsuKey;

public interface RolUsuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol_usu
	 * @mbg.generated  Sat May 16 23:02:23 CEST 2020
	 */
	long countByExample(RolUsuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol_usu
	 * @mbg.generated  Sat May 16 23:02:23 CEST 2020
	 */
	int deleteByExample(RolUsuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol_usu
	 * @mbg.generated  Sat May 16 23:02:23 CEST 2020
	 */
	int deleteByPrimaryKey(RolUsuKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol_usu
	 * @mbg.generated  Sat May 16 23:02:23 CEST 2020
	 */
	int insert(RolUsuKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol_usu
	 * @mbg.generated  Sat May 16 23:02:23 CEST 2020
	 */
	int insertSelective(RolUsuKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol_usu
	 * @mbg.generated  Sat May 16 23:02:23 CEST 2020
	 */
	List<RolUsuKey> selectByExample(RolUsuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol_usu
	 * @mbg.generated  Sat May 16 23:02:23 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") RolUsuKey record, @Param("example") RolUsuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol_usu
	 * @mbg.generated  Sat May 16 23:02:23 CEST 2020
	 */
	int updateByExample(@Param("record") RolUsuKey record, @Param("example") RolUsuExample example);
}