package com.apijccp.dao.mysql.mapper;

import com.apijccp.dao.UsuarioWeb;
import java.util.List;

public interface UsuarioWebMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario_web
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	int deleteByPrimaryKey(Integer idUsuario);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario_web
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	int insert(UsuarioWeb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario_web
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	UsuarioWeb selectByPrimaryKey(Integer idUsuario);
	
	UsuarioWeb selectByUsername(String username);
	
	int selectNextID();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario_web
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	List<UsuarioWeb> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario_web
	 * @mbg.generated  Sun Apr 26 20:04:15 CEST 2020
	 */
	int updateByPrimaryKey(UsuarioWeb record);
}